### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, 

### ISSUE THREAD

**Issue by faltaren** [airdcpp-web/airdcpp-share-monitor#3]
Hey! I get this error and i cant fix it. I have reinstalled dc from scratch and I still get it. Is on windows 10 in a vm on ubuntu. 

Error: EISDIR: illegal operation on a directory, watch 'D:\Media\Movies-1080\'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at fn (C:\Users\XXX\Documents\AirDC++\extensions\airdcpp-share-monitor\package\dist\webpack:\airdcpp-share-monitor\node_modules\node-watch\lib\watch.js:397:22)
    at fn (C:\Users\XXX\Documents\AirDC++\extensions\airdcpp-share-monitor\package\dist\webpack:\airdcpp-share-monitor\node_modules\node-watch\lib\has-native-recursive.js:110:9)
    at u.cleanup (C:\Users\XXX\Documents\AirDC++\extensions\airdcpp-share-monitor\package\dist\webpack:\airdcpp-share-monitor\node_modules\node-watch\lib\has-native-recursive.js:49:24)
    at FSWatcher.<anonymous> (C:\Users\XXX\Documents\AirDC++\extensions\airdcpp-share-monitor\package\dist\webpack:\airdcpp-share-monitor\node_modules\node-watch\lib\has-native-recursive.js:109:13)
    at FSWatcher.emit (events.js:314:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:176:12)

**Comment by peps1** [comment]
The error is saying, that the drive is not supporting the `watch` operation. 

* Is drive D:\ in your setup a network drive?
* What filesystem is it using?
* So the Host machine is Ubuntu but running a VM with Windows? Is the drive passed through from the Ubuntu host directly?

**Comment by faltaren** [comment]
Yes the host is Ubuntu and then i have win 10 with virtual box. Using the shared folder function in virtual box. Im using zfs on my local files but i also have rclone mounts.

**Comment by peps1** [comment]
VirtualBox shared folder feature doesn't support inotify.

Marked as won't fix in
https://www.virtualbox.org/ticket/10660
and a few years later
https://www.virtualbox.org/ticket/14234

For Linux/MacOS/BSD users there seems to be a inotify-forwarder tool ( https://github.com/mhallin/notify-forwarder )
https://blog.codecentric.de/en/2017/08/fix-webpack-watch-virtualbox/

Haven't seen anything for windows though.
